### ISSUE TITLE
Orthographic projection not working. 

### ISSUE THREAD

**Issue by lazarusA** [JuliaPlots/GeoMakie.jl#84] opened 2021-07-04 17:38 UTC
by using "+proj=ortho" in the README example the following error is shown. 

`error message: LoadError: Invalid x-limits (-6.378137f6, Inf32) for scale identity which is defined on the interval -Inf..Inf (open)`

**Comment by visr** [comment] 2021-07-04 17:40
Is that for the source or dest? Are you using the right input units for the chosen projection?

**Comment by lazarusA** [comment] 2021-07-04 17:54
dest

```
source = "+proj=longlat +datum=WGS84"
dest = "+proj=ortho"
trans = Proj4.Transformation(source, dest, always_xy=true)
ptrans = Makie.PointTrans{2}(trans)
```

**Comment by visr** [comment] 2021-07-04 20:49
The othographic projection only shows one half of the globe: https://proj.org/operations/projections/ortho.html
So if you are trying to project points on "the dark side of the Earth", PROJ will give you Infinities back.

Would be nice to just hide this data automatically though, not sure how we should go about that however.

```julia
julia> using Proj4
julia> source = "+proj=longlat +datum=WGS84"
julia> dest = "+proj=ortho"
julia> trans = Proj4.Transformation(source, dest, always_xy=true)
julia> trans((0,0))
2-element StaticArrays.SVector{2, Float64} with indices SOneTo(2):
 0.0
 0.0

julia> trans((90,0))
2-element StaticArrays.SVector{2, Float64} with indices SOneTo(2):
 6.378137e6
 0.0

julia> trans((91,0))
2-element StaticArrays.SVector{2, Float64} with indices SOneTo(2):
 Inf
 Inf
```

Similarly, though not the same, with this projection: https://proj.org/operations/projections/igh.html, for polygons like Greenland and Antarctica, GeoMakie will currently draw a connecting line over the interrupted area, much like the picture on the PROJ website. Clipping them would look nicer however, like here:
https://www.nationalgeographic.org/activity/investigating-map-projections/#goode-homolosine-projection

**Comment by lazarusA** [comment] 2021-07-04 21:06
> Would be nice to just hide this data automatically though
when I want to hide data, I usually just set everything to NaN, lon -> NaN, lat -> NaN. But, yes I see the problem.

**Comment by visr** [comment] 2021-07-05 18:04
closing this as a duplicate of #47

**Closed by visr** 2021-07-05 18:04 UTC
